services:
  postgres:
    image: postgres:13.14-bullseye
    container_name: mysite-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./postgres/.env
    networks:
      - mysite_network
    external: true

  web:
    build: .
    command: /bin/sh start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mysite_network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - mysite_network

volumes:
  postgres_data:
    name: "mysite_postgres_data"

networks:
  mysite_network:
    driver: bridge